### ISSUE TITLE
Trying to open a file provided as an input in a variable

### ISSUE THREAD

**Issue by lianxmfor** [arriqaaq/flashdb#1]
https://github.com/arriqaaq/flashdb/blob/8ca13a6bdd99c4ce0cff0b8b7fafd21784bd6e4f/cmd/server/main.go#L52

Trying to open a file provided as an input in a variable. The content of this variable might be controlled by an attacker who could change it to hold unauthorised file paths from the system. see: https://securego.io/docs/rules/g304.html

**Comment by arriqaaq** [comment]
Thank you for pointing this out @lianxmfor 

Appreciate your time reading the code, pointing this out and creating a fix
