### ISSUE TITLE
FlashDB, flashdb: rename?

### ISSUE THREAD

**Issue by Grabber** [arriqaaq/flashdb#12]
When I got to this project I remembered about this one: https://github.com/armink/FlashDB

Maybe rename to avoid confusions?

**Comment by arriqaaq** [comment]
Thank you for the suggestion @Grabber , I wasn't aware of it. Any suggestions on the naming?

**Comment by Grabber** [comment]
- aoldb (from Append-Only-Log)?
- flashdb-go
- flukedb

Some ideas?

**Comment by arriqaaq** [comment]
Thanks for the suggestion, aoldb is nice but may be confusing because it refers to being an append only log fixated database. I'll keep this open in case a need arises to change it

**Comment by arriqaaq** [comment]
closing this for now
